listen_host = "127.211.73.84"
hosts_ip = "127.211.73.84"
http_port = 80
https_port = 443
upstream = "https://linux.do"
fake_sni = "www.cloudflare.com"
upstream_mode = "auto"

doh_endpoints = [
    "https://aaa.ddd.oaifree.com/query-dns",
]
managed_prefer_ipv6 = false
dns_hosts = {}
edge_node = ""
# example:
# dns_hosts = { "example.com" = "1.1.1.1", "*.example.com" = "domain:real.example.net" }
# edge_node = "2606:4700:10::6814:10ea"

proxy_domains = [
    "linux.do",
    "*.linux.do",
    "idcflare.com",
    "*.idcflare.com",
    "wdbook.com",
    "*.wdbook.com",
    "zzbook.cfd",
    "*.zzbook.cfd",
    "dl.edhub.cc",
    "wedevotebible.org",
    "*.wedevotebible.org",
    "zobook.top",
    "*.zobook.top",
    "qqchat.top",
    "*.qqchat.top",
    "readmoo.com",
    "*.readmoo.com",
    "endao.one",
    "*.endao.one",
    "edbooks.co",
    "*.edbooks.co",
    "ebook.endao.co",
    "isbook.top",
    "*.isbook.top",
    "edbook.app",
    "*.edbook.app",
    "edread.cc",
    "*.edread.cc",
    "i.endao.shop",
    "*.endao.shop",
]

hosts_domains = [
    "linux.do",
    "2048.linux.do",
    "ads.linux.do",
    "autoconfig.linux.do",
    "autodiscover.linux.do",
    "cdk.linux.do",
    "cdn.linux.do",
    "cdn3.linux.do",
    "check.linux.do",
    "connect.linux.do",
    "credit.linux.do",
    "docker-gcr.linux.do",
    "docker-ghcr.linux.do",
    "docker-hub.linux.do",
    "docker-ui.linux.do",
    "go.linux.do",
    "imap.linux.do",
    "ios.linux.do",
    "lottery.linux.do",
    "mail.linux.do",
    "mta-sts.linux.do",
    "nav.linux.do",
    "ping.linux.do",
    "pop.linux.do",
    "pop3.linux.do",
    "pow.linux.do",
    "rate.linux.do",
    "linuxdo-uploads.s3.linux.do",
    "s3.linux.do",
    "smtp.linux.do",
    "status.linux.do",
    "test-bba.s3.linux.do",
    "uptime.linux.do",
    "webmail.linux.do",
    "wiki.linux.do",
    "www.linux.do",
    "idcflare.com",
    "www.idcflare.com",
    "connect.idcflare.com",
    "lottery.idcflare.com",
    "wdbook.com",
    "www.wdbook.com",
    "blog.wdbook.com",
    "zzbook.cfd",
    "e.zzbook.cfd",
    "dl.edhub.cc",
    "wedevotebible.org",
    "www.wedevotebible.org",
    "zobook.top",
    "a.zobook.top",
    "qqchat.top",
    "www.qqchat.top",
    "readmoo.com",
    "www.readmoo.com",
    "ap.readmoo.com",
    "campaign.readmoo.com",
    "cdn.readmoo.com",
    "gateway.readmoo.com",
    "member.readmoo.com",
    "moopub.readmoo.com",
    "new-read.readmoo.com",
    "news.readmoo.com",
    "next.readmoo.com",
    "podcast.readmoo.com",
    "read.readmoo.com",
    "report.readmoo.com",
    "share.readmoo.com",
    "endao.one",
    "www.endao.one",
    "edbooks.co",
    "www.edbooks.co",
    "ebook.endao.co",
    "isbook.top",
    "www.isbook.top",
    "edbook.app",
    "www.edbook.app",
    "edread.cc",
    "www.edread.cc",
    "i.endao.shop",
]

certificate_domains = [
    "linux.do",
    "www.linux.do",
    "*.linux.do",
    "*.s3.linux.do",
    "idcflare.com",
    "www.idcflare.com",
    "*.idcflare.com",
    "wdbook.com",
    "www.wdbook.com",
    "*.wdbook.com",
    "zzbook.cfd",
    "e.zzbook.cfd",
    "*.zzbook.cfd",
    "dl.edhub.cc",
    "wedevotebible.org",
    "*.wedevotebible.org",
    "zobook.top",
    "a.zobook.top",
    "*.zobook.top",
    "qqchat.top",
    "www.qqchat.top",
    "*.qqchat.top",
    "readmoo.com",
    "www.readmoo.com",
    "*.readmoo.com",
    "endao.one",
    "www.endao.one",
    "*.endao.one",
    "edbooks.co",
    "www.edbooks.co",
    "*.edbooks.co",
    "ebook.endao.co",
    "isbook.top",
    "www.isbook.top",
    "*.isbook.top",
    "edbook.app",
    "www.edbook.app",
    "*.edbook.app",
    "edread.cc",
    "www.edread.cc",
    "*.edread.cc",
    "i.endao.shop",
    "*.endao.shop",
]

ca_common_name = "Jireh Accelerator Root CA"
server_common_name = "linux.do"

[domain_modes]
"linux.do" = "ech"
"*.linux.do" = "ech"
"idcflare.com" = "ech"
"*.idcflare.com" = "ech"
"wdbook.com" = "ech"
"*.wdbook.com" = "ech"
"zzbook.cfd" = "ech"
"*.zzbook.cfd" = "ech"
"dl.edhub.cc" = "ech"
"wedevotebible.org" = "ech"
"*.wedevotebible.org" = "ech"
"zobook.top" = "ech"
"*.zobook.top" = "ech"
"qqchat.top" = "ech"
"*.qqchat.top" = "ech"
"readmoo.com" = "sni"
"*.readmoo.com" = "sni"
"endao.one" = "ech"
"*.endao.one" = "ech"
"edbooks.co" = "ech"
"*.edbooks.co" = "ech"
"ebook.endao.co" = "ech"
"isbook.top" = "ech"
"*.isbook.top" = "ech"
"edbook.app" = "ech"
"*.edbook.app" = "ech"
"edread.cc" = "ech"
"*.edread.cc" = "ech"
"i.endao.shop" = "ech"
"*.endao.shop" = "ech"
